x-app: &app
  build:
    context: ..
    dockerfile: .dockerdev/Dockerfile
    args:
      RUBY_VERSION: '4.0'
  image: mastodon-dev:1.0.0
  # Use a pre-built image (with gems installed) instead of building locally:
  # comment out the `build` section above and specify the registry image, e.g.:
  # image: palkan/mastodon-test-prof:2.0.0
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
  tmpfs:
    # NOTE: Yarn executes script shims from $TMPDIR, so /tmp must be mounted with exec
    - /tmp:exec
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - rails_cache:/app/tmp/cache
    - rails_logs:/app/log
    - node_modules:/app/node_modules
    - history:/usr/local/hist
    - storage:/app/public/system
    - ./.psqlrc:/root/.psqlrc:ro
    - ./.bashrc:/root/.bashrc:ro
  environment: &backend_environment
    <<: *env
    BIND: 0.0.0.0
    REDIS_HOST: redis
    REDIS_PORT: '6379'
    DB_HOST: postgres
    DB_USER: postgres
    DB_PASS: postgres
    DB_PORT: '5432'
    ES_ENABLED: 'false'
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    BOOTSNAP_CACHE_DIR: /app/tmp/cache/bootsnap
    XDG_DATA_HOME: /app/tmp/cache
    YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
    HISTFILE: /usr/local/hist/.bash_history
    PSQL_HISTFILE: /usr/local/hist/.psql_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    EDITOR: vi
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  rails:
    <<: *backend
    command: bundle exec rails

  rails-isolated:
    extends:
      service: rails
    volumes:
      - gitstub:/app/.git
    networks: [ isolated ]

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - history:/usr/local/hist
    environment:
      PSQL_HISTFILE: /usr/local/hist/.psql_history
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    networks: [ default, isolated ]

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    networks: [ default, isolated ]

networks:
  isolated:
    internal: true

volumes:
  node_modules:
  history:
  rails_cache:
  rails_logs:
  postgres:
  redis:
  storage:
  gitstub:
